import { promises as fs } from "node:fs";
import path from "node:path";
import { AgentProfile } from "./types.js";

const BEGIN_MARKER = "<!-- AGENTSHELL:BEGIN -->";
const END_MARKER = "<!-- AGENTSHELL:END -->";

export type AgentConfigTarget = "claude" | "agents";

export interface InjectionOptions {
  profile: AgentProfile;
  projectRoot: string;
  targets?: AgentConfigTarget[];
  mcpServerUrl?: string;
  mcpTools?: McpToolDescription[];
  updatedAt?: Date;
}

export interface InjectionResult {
  target: AgentConfigTarget;
  path: string;
  validation: ValidationResult;
}

interface MarkerWriteResult {
  block: string;
  fileContent: string;
}

export interface ValidationResult {
  valid: boolean;
  failures: string[];
}

export interface McpToolDescription {
  name: string;
  description: string;
}

const DEFAULT_MCP_TOOLS: McpToolDescription[] = [
  { name: "knowledge.search", description: "检索 Obsidian 工作知识库" },
  { name: "knowledge.skills", description: "列出内置知识库搭建/写入 Skill" },
  { name: "knowledge.outline", description: "读取工作知识库分类大纲和模板说明" },
  { name: "knowledge.detectObsidianVault", description: "检测当前知识库是否已是 Obsidian Vault" },
  { name: "knowledge.recommendNoteStrategy", description: "建议笔记是共享文档、拆分文档还是先粗捕获" },
  { name: "knowledge.planNoteWrite", description: "在写入前计划分类、策略和 Vault 模式" },
  { name: "knowledge.get", description: "读取知识库中的指定 Markdown 文件" },
  { name: "knowledge.documents", description: "列出知识库分类卡片和 Markdown 文档摘要" },
  { name: "knowledge.readDocumentForUi", description: "读取 Markdown、简化源码显示并返回附件/引用元数据" },
  { name: "knowledge.getSection", description: "按 H2 标题精准读取单个 Markdown 章节" },
  { name: "knowledge.sections", description: "列出 Markdown 的 H2 目录和短摘录" },
  { name: "knowledge.projects", description: "列出 01-项目 下的项目" },
  { name: "knowledge.loadProject", description: "加载项目 AI索引.md 背景" },
  { name: "knowledge.contextRules", description: "列出 AI 上下文触发词、别名和优先级规则" },
  { name: "knowledge.planContext", description: "根据用户问题规划应该读取哪些知识库上下文" },
  { name: "knowledge.loadContextPlan", description: "按上下文规划读取 Markdown 内容" },
  { name: "knowledge.createProject", description: "创建项目知识库结构" },
  { name: "knowledge.createIteration", description: "创建项目迭代记录" },
  { name: "knowledge.classifyEntry", description: "根据内容给出知识条目归档建议" },
  { name: "knowledge.store", description: "写入或追加知识条目" },
  { name: "knowledge.prepareEdit", description: "把 Markdown 选区解析成 AI 编辑上下文卡片" },
  { name: "knowledge.previewEdit", description: "预览 Markdown 选区替换并返回红绿 diff 数据" },
  { name: "knowledge.applyEdit", description: "用户确认后应用 Markdown 选区替换" },
  { name: "knowledge.attachAsset", description: "复制图片/PDF到项目 attachments 并插入 Markdown 嵌入链接" },
  { name: "knowledge.updateSection", description: "替换或追加指定 H2 章节内容" },
  { name: "knowledge.inbox", description: "列出收件箱待整理内容并生成整理选择" },
  { name: "knowledge.healthCheck", description: "检查知识库结构和更新状态" },
  { name: "knowledge.repairHealthIssue", description: "修复单个健康检查问题" },
  { name: "knowledge.recommendObsidianConnector", description: "推荐使用现成的 Obsidian MCP/REST 连接器" },
  { name: "knowledge.checkObsidianConnector", description: "检测 Obsidian 连接器版本漂移和兼容性" },
  { name: "knowledge.setObsidianConnectorSnapshot", description: "保存 Obsidian 连接器当前版本快照" },
  { name: "agentshell.injectConfig", description: "向 CLAUDE.md / AGENTS.md 注入 AgentShell Profile" },
];

export async function injectAgentShellConfig(options: InjectionOptions): Promise<InjectionResult[]> {
  const targets = options.targets ?? ["claude", "agents"];
  const results: InjectionResult[] = [];

  for (const target of targets) {
    const relativePath = target === "claude" ? "CLAUDE.md" : "AGENTS.md";
    const filePath = path.join(options.projectRoot, relativePath);
    const content = target === "claude"
      ? generateClaudeMd(options)
      : generateAgentsMd(options);

    await fs.mkdir(path.dirname(filePath), { recursive: true });
    const writeResult = await writeWithMarker(filePath, content);
    results.push({ target, path: filePath, validation: validateInjectedContent(writeResult.block, writeResult.fileContent) });
  }

  return results;
}

export function generateClaudeMd(options: Omit<InjectionOptions, "projectRoot" | "targets">): string {
  const data = buildTemplateData(options);
  const sections = [
    `# AgentShell 配置\n> 由 AgentShell 自动生成，请勿手动修改标记块内的内容。\n> 最后更新：${data.updatedAt}\n\n---`,
    renderClaudeIdentity(data),
    renderClaudeSkills(data),
    renderClaudeMemory(data),
    renderClaudeKnowledge(data),
    renderClaudeConstraints(),
    renderClaudeMcp(data),
  ].filter(Boolean);

  return enforceLength(sections.join("\n\n"));
}

export function generateAgentsMd(options: Omit<InjectionOptions, "projectRoot" | "targets">): string {
  const data = buildTemplateData(options);
  const sections = [
    `# AgentShell Configuration\n> Auto-generated by AgentShell. Do not edit content within marker blocks.\n> Last updated: ${data.updatedAt}\n\n---`,
    renderAgentsIdentity(data),
    renderAgentsSkills(data),
    renderAgentsMemory(data),
    renderAgentsKnowledge(data),
    renderAgentsConstraints(),
    renderAgentsMcp(data),
  ].filter(Boolean);

  return enforceLength(sections.join("\n\n"));
}

export async function writeWithMarker(filePath: string, newContent: string): Promise<MarkerWriteResult> {
  const normalizedContent = stripMarkers(newContent).trim();
  const block = `${BEGIN_MARKER}\n${normalizedContent}\n${END_MARKER}`;

  let existing = "";
  try {
    existing = await fs.readFile(filePath, "utf-8");
  } catch (error) {
    if (isNodeError(error) && error.code === "ENOENT") {
      const fileContent = `${block}\n`;
      await fs.writeFile(filePath, fileContent, "utf-8");
      return { block, fileContent };
    }
    throw error;
  }

  const markerState = findMarkerState(existing);
  let fileContent: string;

  if (markerState.validPair) {
    const before = existing.slice(0, markerState.validPair.beginIndex);
    const after = existing.slice(markerState.validPair.endIndex + END_MARKER.length);
    fileContent = `${before}${block}${after}`;
  } else {
    const repaired = stripAllMarkerLines(existing).trimEnd();
    const separator = repaired.trim().length ? "\n\n" : "";
    fileContent = `${repaired}${separator}${block}\n`;
  }

  await fs.writeFile(filePath, fileContent, "utf-8");
  return { block, fileContent };
}

export function validateInjectedContent(content: string, fileContent = content): ValidationResult {
  const markerState = findMarkerState(fileContent);
  const checks = [
    {
      name: "包含身份定义",
      pass: content.includes("你现在扮演的角色是") || content.includes("You are acting as"),
    },
    {
      name: "至少有一条行为约束",
      pass: content.includes("必须遵守") || content.includes("Must:"),
    },
    {
      name: "包含唯一有效标记块",
      pass: markerState.beginIndexes.length === 1 && markerState.endIndexes.length === 1 && Boolean(markerState.validPair),
    },
    {
      name: "内容长度合理（不超过4000字）",
      pass: content.length <= 4000,
    },
    {
      name: "MCP Server 地址已填入",
      pass: hasValidMcpEndpoint(content),
    },
  ];

  const failures = checks.filter((check) => !check.pass).map((check) => check.name);
  return { valid: failures.length === 0, failures };
}

interface TemplateData {
  updatedAt: string;
  identity: Required<AgentProfile["identity"]>;
  skills: Array<Required<NonNullable<AgentProfile["skills"]>[number]>>;
  memory: { enabled: boolean; scope: NonNullable<AgentProfile["memoryScope"]> };
  knowledgeBases: Array<Required<NonNullable<AgentProfile["knowledgeBases"]>[number]>>;
  mcpServerUrl: string;
  mcpTools: McpToolDescription[];
}

function buildTemplateData(options: Omit<InjectionOptions, "projectRoot" | "targets">): TemplateData {
  const profile = options.profile;
  return {
    updatedAt: formatDateTime(options.updatedAt ?? new Date()),
    identity: {
      role: profile.identity.role,
      systemPrompt: truncate(profile.identity.systemPrompt, 600),
      guidelines: profile.identity.guidelines ?? [],
      responseStyle: profile.identity.responseStyle ?? "balanced",
      thinkingDepth: profile.identity.thinkingDepth ?? "standard",
    },
    skills: (profile.skills ?? [])
      .filter((skill) => skill.enabled !== false)
      .slice(0, 8)
      .map((skill) => ({
        name: skill.name,
        triggers: skill.triggers,
        description: skill.description,
        promptTemplate: skill.promptTemplate ?? "",
        requireConfirm: skill.requireConfirm ?? false,
        enabled: skill.enabled ?? true,
      })),
    memory: {
      enabled: (profile.memoryScope ?? "none") !== "none",
      scope: profile.memoryScope ?? "none",
    },
    knowledgeBases: (profile.knowledgeBases ?? []).slice(0, 5).map((kb) => ({
      id: kb.id,
      name: kb.name,
      description: kb.description,
      retrievalTopK: kb.retrievalTopK ?? 5,
      usageScenario: kb.usageScenario ?? "仅当用户明确聊到某个公司项目、产品、项目背景、功能、优势、定位或历史决策时检索；普通聊天、个人文章、草稿和非项目内容默认不检索。",
    })),
    mcpServerUrl: options.mcpServerUrl ?? `stdio: obsidian-knowledge-mcp`,
    mcpTools: (options.mcpTools ?? DEFAULT_MCP_TOOLS).slice(0, 10),
  };
}

function renderClaudeIdentity(data: TemplateData): string {
  const guidelines = data.identity.guidelines.length
    ? `\n### 行为准则\n${data.identity.guidelines.map((item, index) => `${index + 1}. ${item}`).join("\n")}`
    : "";

  return `## 🪪 当前身份\n\n你现在扮演的角色是：**${data.identity.role}**\n\n${data.identity.systemPrompt}${guidelines}\n\n### 参数设定\n- 回复风格：${mapResponseStyle(data.identity.responseStyle)}\n- 思考深度：${mapThinkingDepth(data.identity.thinkingDepth)}`;
}

function renderClaudeSkills(data: TemplateData): string {
  if (!data.skills.length) return "";

  return `## 🛠️ 可用技能\n\n你拥有以下技能，当用户的请求匹配触发条件时，主动使用对应技能：\n\n${data.skills.map((skill) => {
    const template = skill.promptTemplate ? `\n**执行模板：**\n${truncate(skill.promptTemplate, 500)}` : "";
    const confirm = skill.requireConfirm ? "\n⚠️ 执行前必须通过 AgentShell 向用户确认，不得自行决定执行。" : "";
    return `### ${skill.name}\n**触发条件：** ${skill.triggers.join("、")}\n**执行方式：** ${skill.description}${template}${confirm}`;
  }).join("\n\n---\n\n")}`;
}

function renderClaudeMemory(data: TemplateData): string {
  if (!data.memory.enabled) return "";

  const storeSection = data.memory.scope === "session" ? "" : `\n\n**写入记忆（对话结束时）：**\n- 工具：\`memory://store\`\n- 触发条件：用户明确表达了偏好、做出了重要决策、提供了新的背景信息\n- 禁止：不要把所有对话都写入记忆，只保留有价值的信息`;
  const scopeNote = data.memory.scope === "project"
    ? "\n- 当前作用域为项目级，记忆仅在当前工作区有效"
    : data.memory.scope === "user"
      ? "\n- 当前作用域为用户级，记忆跨所有项目共享"
      : "\n- 当前作用域为会话级，对话结束后记忆自动清空";

  return `## 🧠 记忆系统\n\n你可以通过以下方式访问和写入记忆：\n\n**读取记忆（对话开始时）：**\n- 工具：\`memory://recent?limit=5\`\n- 用途：了解最近几次对话的关键信息，避免用户重复解释\n\n**语义检索（需要历史信息时）：**\n- 工具：\`memory://search?q={关键词}\`\n- 用途：查找用户过去提到过的偏好、决策、背景信息\n- 原则：只在确实需要时检索，不要每轮对话都检索${storeSection}\n\n**记忆作用域：** ${data.memory.scope}${scopeNote}`;
}

function renderClaudeKnowledge(data: TemplateData): string {
  if (!data.knowledgeBases.length) return "";

  return `## 📖 知识库\n\n你可以访问以下知识库，但只在用户问题明确涉及公司项目或产品时检索：\n\n${data.knowledgeBases.map((kb) => `### ${kb.name}\n- **内容范围：** ${kb.description}\n- **检索工具：** \`knowledge://search?vault=${kb.id}&q={关键词}&k=${kb.retrievalTopK}&scope=projects\`\n- **直接读取：** \`knowledge://get?vault=${kb.id}&path={文件路径}\`\n- **适用场景：** ${kb.usageScenario}`).join("\n\n")}\n\n**知识库使用原则：**\n1. 默认只检索 \`01-项目\`，也就是公司项目知识库\n2. 只有用户提到具体项目、公司产品、项目背景、功能、优势、定位、页面分析等内容时才检索\n3. 用户自己的文章、草稿、个人资料、非项目内容默认不检索，除非用户明确要求“搜整个知识库”或点名对应文件\n4. 长文档先用 \`knowledge.sections\` 看目录，再用 \`knowledge.getSection\` 精准读取\n5. 写入前先判断是否属于项目；不属于项目且用户未要求入库时，不主动创建目录或检索\n6. 引用知识库内容时，标注来源文件名`;
}

function renderClaudeConstraints(): string {
  return `## ⚙️ 行为约束\n\n### 必须遵守\n1. 执行任何写入操作前，必须先告知用户将要做什么\n2. 触发技能执行时，等待 AgentShell 的用户确认信号，不得自行跳过确认步骤\n3. 引用知识库内容时，标注来源\n4. 不确定用户意图时，提出最多一个澄清问题，而不是列出多个假设\n\n### 禁止行为\n1. 不得一次性读取整个知识库的所有文件\n2. 不得在用户未明确要求时主动修改已有文件\n3. 不得忽略 AgentShell 的确认请求直接执行技能\n4. 不得在会话中承诺记忆会跨会话保留（除非作用域是用户级或项目级）`;
}

function renderClaudeMcp(data: TemplateData): string {
  return `## 🔌 MCP Server 连接\n\nAgentShell 本地 MCP Server 地址：\`${data.mcpServerUrl}\`\n\n可用工具列表：\n${data.mcpTools.map((tool) => `- \`${tool.name}\`：${tool.description}`).join("\n")}`;
}

function renderAgentsIdentity(data: TemplateData): string {
  const guidelines = data.identity.guidelines.length
    ? `\n\nGuidelines:\n${data.identity.guidelines.map((item) => `- ${item}`).join("\n")}`
    : "";

  return `## Identity\n\nYou are acting as: **${data.identity.role}**\n\n${data.identity.systemPrompt}${guidelines}`;
}

function renderAgentsSkills(data: TemplateData): string {
  if (!data.skills.length) return "";

  return `## Available Skills\n\nUse the following skills when user requests match the trigger conditions:\n\n${data.skills.map((skill) => `**${skill.name}**\n- Trigger: ${skill.triggers.join(", ")}\n- Action: ${skill.description}${skill.requireConfirm ? "\n- ⚠️ Requires user confirmation via AgentShell before execution" : ""}`).join("\n\n")}`;
}

function renderAgentsMemory(data: TemplateData): string {
  if (!data.memory.enabled) return "";

  const store = data.memory.scope === "session" ? "" : "\n- Store important info: `memory://store`";
  return `## Memory\n\n- Read recent context: \`memory://recent?limit=5\`\n- Semantic search: \`memory://search?q={query}\`${store}\n- Scope: ${data.memory.scope}`;
}

function renderAgentsKnowledge(data: TemplateData): string {
  if (!data.knowledgeBases.length) return "";

  return `## Knowledge Bases\n\nUse these knowledge bases only when the user is discussing company projects or products:\n\n${data.knowledgeBases.map((kb) => `- **${kb.name}**: \`knowledge://search?vault=${kb.id}&q={query}&k=${kb.retrievalTopK}&scope=projects\`\n  Coverage: ${kb.description}`).join("\n")}\n\nRules:\n- Default search scope is \`01-项目\` only\n- Search only when the user mentions a specific project, company product, project background, features, advantages, positioning, or page/design analysis\n- Do not search personal articles, drafts, or non-project notes by default unless the user explicitly asks to search the whole vault or names a file\n- Use \`knowledge.sections\` before reading long files, then \`knowledge.getSection\`\n- Cite the source file when referencing knowledge base content`;
}

function renderAgentsConstraints(): string {
  return `## Constraints\n\nMust:\n- Announce write operations before executing\n- Wait for AgentShell confirmation before triggering skills\n- Ask at most one clarifying question when intent is unclear\n\nMust not:\n- Read entire knowledge base at once\n- Modify files without explicit user request\n- Skip AgentShell confirmation steps`;
}

function renderAgentsMcp(data: TemplateData): string {
  return `## MCP Server\n\nEndpoint: \`${data.mcpServerUrl}\`\n\nAvailable tools:\n${data.mcpTools.map((tool) => `- \`${tool.name}\`: ${tool.description}`).join("\n")}`;
}

function mapResponseStyle(style: Required<AgentProfile["identity"]>["responseStyle"]): string {
  const labels = {
    concise: "简洁，每次回复控制在 300 字以内，优先给结论",
    balanced: "均衡，结论 + 关键理由，避免冗长铺垫",
    detailed: "详尽，提供完整分析过程和多个角度",
  };
  return labels[style];
}

function mapThinkingDepth(depth: Required<AgentProfile["identity"]>["thinkingDepth"]): string {
  const labels = {
    quick: "快速响应，直接给出最可能的答案",
    standard: "标准思考，权衡主要选项后给出建议",
    deep: "深度分析，逐步拆解问题，考虑边界情况",
  };
  return labels[depth];
}

function enforceLength(content: string): string {
  if (content.length <= 4000) return content;
  return content.slice(0, 3900).trimEnd() + "\n\n（注入内容已截断，完整版本请查看 AgentShell Profile 配置）";
}

function stripMarkers(content: string): string {
  return content.replace(BEGIN_MARKER, "").replace(END_MARKER, "");
}

function stripAllMarkerLines(content: string): string {
  return content
    .split(/\r?\n/)
    .filter((line) => line.trim() !== BEGIN_MARKER && line.trim() !== END_MARKER)
    .join("\n");
}

function findMarkerState(content: string): {
  beginIndexes: number[];
  endIndexes: number[];
  validPair?: { beginIndex: number; endIndex: number };
} {
  const beginIndexes = findAllIndexes(content, BEGIN_MARKER);
  const endIndexes = findAllIndexes(content, END_MARKER);
  const beginIndex = beginIndexes[0];
  const endIndex = endIndexes.find((candidate) => beginIndex !== undefined && candidate > beginIndex);
  const validPair = beginIndexes.length === 1 && endIndexes.length === 1 && beginIndex !== undefined && endIndex !== undefined
    ? { beginIndex, endIndex }
    : undefined;

  return { beginIndexes, endIndexes, validPair };
}

function findAllIndexes(content: string, marker: string): number[] {
  const indexes: number[] = [];
  let index = content.indexOf(marker);
  while (index !== -1) {
    indexes.push(index);
    index = content.indexOf(marker, index + marker.length);
  }
  return indexes;
}

function hasValidMcpEndpoint(content: string): boolean {
  const endpoint = content.match(/(?:地址|Endpoint)：?\s*`([^`]+)`/)?.[1];
  if (!endpoint) return false;
  if (endpoint.startsWith("stdio:")) return true;

  try {
    const url = new URL(endpoint);
    return url.protocol === "http:" || url.protocol === "https:";
  } catch {
    return endpoint.trim().length > 0;
  }
}

function truncate(value: string, maxLength: number): string {
  if (value.length <= maxLength) return value;
  return value.slice(0, maxLength - 20) + "（已截断）";
}

function formatDateTime(date: Date): string {
  return new Intl.DateTimeFormat("zh-CN", {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  }).format(date).replaceAll("/", "-");
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && "code" in error;
}
